=  Chapter 7. Creating binary packages
:toc:
:toc: left
:toclevels: 4
:docinfo: private

==  7.1. Building a single binary package

Once you have built and installed a package, you can create a __binary package__ which can be installed on another system with http://man.NetBSD.org/NetBSD-9.2/i386/pkg_add.1[pkg_add(1)].This saves having to build the same package on a group of hosts and wasting CPU time. It also provides a simple means for others to install your package, should you distribute it.

To create a binary package, change into the appropriate directory in pkgsrc, and run **make package**:

    $ cd misc/figlet
    $ make package

This will build and install your package (if not already done), and then build a binary package from what was installed. You can then use the **pkg_*** tools to manipulate it.Binary packages are created by default in ``/usr/pkgsrc/packages``, in the form of a gzipped tar file. See http://netbsd.org/docs/pkgsrc/logs.html#logs.package[Section C.2, “Packaging figlet”] for a continuation of the above https://cdn.NetBSD.org/pub/pkgsrc/current/pkgsrc/misc/figlet/index.html[``misc/figlet``] example. 

See http://netbsd.org/docs/pkgsrc/submit.html[Chapter 23, Submitting and Committing] for information on how to submit such a binary package.

==  7.2. Settings for creation of binary packages

See http://netbsd.org/docs/pkgsrc/build.html#build.helpful-targets[Section 13.17, “Other helpful targets”].
