= Chapter 2. Getting help
:toc:
:toc: left
:toclevels: 4
:docinfo: private

To get help when using pkgsrc, the definitive source is this
	document, the pkgsrc guide. If you don't find anything here,
	there are alternatives:

*   The built-in pkgsrc help, which is available after bootstrapping
	pkgsrc. Run **bmake help topic=…** to get
	help for any topic, such as a variable name like
	``BUILD_DEFS``, a make target like
	**do-build**, a missing C or C++ function like
	**strcasecmp** or any other topic.

The available help topics are listed in http://netbsd.org/docs/pkgsrc/help-topics.html[Appendix E, Help topics].

*   To see the value of a single variable, run **bmake
	show-var VARNAME=__``X``__**.

*   To see the values of the most common variables, run
	**bmake show-all**. These variables are grouped by
	topic. To see the variables for a single topic, run
	**bmake
	show-all-__``topic``__**, for example
	**bmake show-all-fetch**.

*   The pkgsrc-users mailing list, to which
	https://www.NetBSD.org/mailinglists/#pkgsrc-users[you
	can subscribe] and then mailto:pkgsrc-users@NetBSD.org[ask your
	questions].

*   The #pkgsrc IRC channel, which is accessible
	https://webchat.freenode.net/[via a web browser]
	or by using a specialized chat program such as
	http://xchat.org/[XChat].
	Pick any user name and join the channel #pkgsrc.
	
.Next 
Chapter 3. Where to get pkgsrc and how to keep it up-to-date xref:chapter-03.adoc[xrefstyle=basic]

.Previous
Chapter 1. What is pkgsrc? xref:chapter-01.adoc[xrefstyle=basic]
